### ISSUE TITLE
AsanaExporter only exporting minor part of all tasks

### ISSUE THREAD

**Issue by lucvandenende-geronimo** [plswiderski/asanaexporter#13]
Hi Pawel,

In september 2020 I have successfully used the AsanaExporter v1.1.0 tool to export all tasks in my projects to a CSV. Thank you for that!

Unfortunately, when I perform the same task now, there are only a minor part of the tasks (or even no tasks) stored in the CSV. My command prompt looks as follows:
![image](https://user-images.githubusercontent.com/74239658/98658161-06468d00-2343-11eb-88db-7e522a8d0b49.png)

Could you check if you have the same issue? Could it be that Asana changed their API?

Thanks a lot!
Luc

**Comment by pablo127** [comment]
Hi Luc,
I have not spotted `Could not find subtask` in logs. It is probably related to your asana's tasks.
Could you find in your csv that id? It should be id of the parent task.

I've also noticed that sometimes not all tasks are downloaded. I will try to track down the problem.

**Comment by lucvandenende-geronimo** [comment]
Hi Pawel,

Thanks for your response!

Those task id's are indeed in the csv and have no subtasks related to them. So that might be normal behaviour.

The issue might lie more in the fact that only 52 tasks were imported, while there are many more tasks (over 4000).

Best regards and thanks again,
Luc

**Comment by lucvandenende-geronimo** [comment]
Hi Pawel,

Have you seen the time to looking into the issue a bit more?

Best regards,
Luc

**Comment by plswiderski** [comment]
Hi Luc,
I cannot give you any estimation. I think the earliest time that I will start work on this, will be at the beginning of the next year.

**Comment by plswiderski** [comment]
Hi Luc. I've made some fixes related to timeouts and better logging.

Please test SNAPSHOT version https://pablo127.bitbucket.io/asanaexporter/asanaexporter-all-1.1.1-SNAPSHOT.jar
and let me know is everything works fine for you.

Please mind that if you run asanaexporter jar from the directory that contains `lastModification.txt` file, program reads it and import only tasks modified not before that date. If you want to import all tasks from Asana workspace (default or given), just delete this file.

**Comment by lucvandenende-geronimo** [comment]
Hi Pawel,

It works! Thanks so much for taking the time for me.

All the best and thanks again,
Luc

**Comment by plswiderski** [comment]
I am happy to hear that.

Have a nice day!
