### ISSUE TITLE
Error: "Main.java:80"; "Error occurred while running AsanaExporter"

### ISSUE THREAD

**Issue by MatiasVDrejer** [plswiderski/asanaexporter#14]
Hi Pawel,

Thanks for building an awesome app.

When executing the app, I get the following error message: `ERROR [main] (Main.java:80) - Error occurred while running AsanaExporter.`

I've validated that the personal access token that I am using is valid with a curl request: `curl https://app.asana.com/api/1.0/users/me \
  -H "Authorization: Bearer 0/123456789abcdef"`

This is the command that I am calling:` java -jar /Applications/asanaexporter-all-1.1.0.jar $1/1234538506617382:abce2f60d9a4d0f6aa69a75ad3418ef2`

**Comment by plswiderski** [comment]
Hi Matias.
Personal token that you are providing looks good. Is there any more information in logs?

Your problem can be related to reported one #13

**Comment by MatiasVDrejer** [comment]
Hi,

This is log the log file I get when executing the command

`WARN [main] (Main.java:89) - Could not load lastModification.txt. All tasks will be downloaded.
ERROR [main] (Main.java:80) - Error occurred while running AsanaExporter.
java.lang.RuntimeException: Could not find workspace with name Personal Projects
	at io.bitbucket.pablo127.asanaexporter.UserDownloadCommand.lambda$run$1(UserDownloadCommand.java:54)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at io.bitbucket.pablo127.asanaexporter.UserDownloadCommand.run(UserDownloadCommand.java:54)
	at io.bitbucket.pablo127.asanaexporter.Main.<init>(Main.java:210)
	at io.bitbucket.pablo127.asanaexporter.Main.main(Main.java:60)`

The Asana profile contains one workspace

**Comment by plswiderski** [comment]
It looks like you don't have `Personal Projects` on your Asana's account.
Click here in Asana GUI:
![asanaAccount](https://user-images.githubusercontent.com/3409023/104850535-08533c00-58f0-11eb-9055-ee919c539d14.PNG)
there is a list of the workspaces.

You can select other than default (Personal projects) by providing its name as an argument to the run command.

e.g.

`java -jar /Applications/asanaexporter-all-1.1.0.jar $1/1234538506617382:abce2f60d9a4d0f6aa69a75ad3418ef2 "workspace Name"`

**Comment by MatiasVDrejer** [comment]
Yeah, I don't have a workspace called Personal Projects.

When I run the command with a specified workspace ie. "pl-partners.dk", the script is able to be executed. I looked through the code earlier and saw that you have hardcoded the workspace "Personal project" - is this the default workspace created by Asana?

**Comment by plswiderski** [comment]
`Personal Projects` is a default one but now I am confused that you don't have it. Maybe it depends on the account type or sth.
Anyway great to hear that exporter works :)
